### ISSUE TITLE
Installation failed！

### ISSUE THREAD

**Issue by Xiaosesh** [hanbufei/findUriInjs#2]
Error: Unsupported Java version type, please check your version and try again

**Comment by Xiaosesh** [comment]
and How to restore default initial rules?

**Comment by hanbufei** [comment]
> and How to restore default initial rules?

"/src/main/java/burp/BurpExtender.java"  line  570 - 579 , here ！ you can  change default initial rules

**Comment by hanbufei** [comment]
> Error: Unsupported Java version type, please check your version and try again

which version you use ? 
you can change Java version in pom.xml ,and  compile
